services:
  ccz-spring:
    build: 
      context: .
      dockerfile: spring/Dockerfile
    container_name: ccz-spring
    ports: ["8080:8080"]
    networks: [shared_network]

  ccz-expo:
    build:
      context: ./ccz-expo
      dockerfile: Dockerfile
    container_name: ccz-expo
    ports: ["8081:80"]
    networks: [shared_network]

networks:
  shared_network:
    driver: bridge
